### ClimateWins Weather Prediction: Keras Layered Model (CNN)

#### 1. Import Libraries and Data

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import os
import operator
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras
from numpy import unique
from numpy import reshape
from keras.models import Sequential
from keras.layers import Conv1D, Conv2D, Dense, BatchNormalization, Flatten, MaxPooling1D, Dropout
from keras.utils import to_categorical
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

import warnings
warnings.filterwarnings("ignore")

In [3]:
# Set display options to show all columns

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [4]:
# Create path for faster data importation
# Create a path for faster data importation
path = r'C:\Users\harip\Desktop\Data Analytics Project\Machine Learning with Python\Exercise 2.2'
unscaled= pd.read_csv(os.path.join(path, '02 Data', 'Original Data', 'climate_dataset.csv'))
prediction = pd.read_csv(os.path.join(path, '02 Data', 'Original Data', 'Pleasant_Weather.csv'))
# confirm import
unscaled.head()

,DATE,MONTH,BASEL_cloud_cover,BASEL_wind_speed,BASEL_humidity,BASEL_pressure,BASEL_global_radiation,BASEL_precipitation,BASEL_snow_depth,BASEL_sunshine,BASEL_temp_mean,BASEL_temp_min,BASEL_temp_max,BELGRADE_cloud_cover,BELGRADE_humidity,BELGRADE_pressure,BELGRADE_global_radiation,BELGRADE_precipitation,BELGRADE_sunshine,BELGRADE_temp_mean,BELGRADE_temp_min,BELGRADE_temp_max,BUDAPEST_cloud_cover,BUDAPEST_humidity,BUDAPEST_pressure,BUDAPEST_global_radiation,BUDAPEST_precipitation,BUDAPEST_sunshine,BUDAPEST_temp_mean,BUDAPEST_temp_min,BUDAPEST_temp_max,DEBILT_cloud_cover,DEBILT_wind_speed,DEBILT_humidity,DEBILT_pressure,DEBILT_global_radiation,DEBILT_precipitation,DEBILT_sunshine,DEBILT_temp_mean,DEBILT_temp_min,DEBILT_temp_max,DUSSELDORF_cloud_cover,DUSSELDORF_wind_speed,DUSSELDORF_humidity,DUSSELDORF_pressure,DUSSELDORF_global_radiation,DUSSELDORF_precipitation,DUSSELDORF_snow_depth,DUSSELDORF_sunshine,DUSSELDORF_temp_mean,DUSSELDORF_temp_min,DUSSELDORF_temp_max,GDANSK_cloud_cover,GDANSK_humidity,GDANSK_precipitation,GDANSK_snow_depth,GDANSK_temp_mean,GDANSK_temp_min,GDANSK_temp_max,HEATHROW_cloud_cover,HEATHROW_humidity,HEATHROW_pressure,HEATHROW_global_radiation,HEATHROW_precipitation,HEATHROW_snow_depth,HEATHROW_sunshine,HEATHROW_temp_mean,HEATHROW_temp_min,HEATHROW_temp_max,KASSEL_wind_speed,KASSEL_humidity,KASSEL_pressure,KASSEL_global_radiation,KASSEL_precipitation,KASSEL_sunshine,KASSEL_temp_mean,KASSEL_temp_min,KASSEL_temp_max,LJUBLJANA_cloud_cover,LJUBLJANA_wind_speed,LJUBLJANA_humidity,LJUBLJANA_pressure,LJUBLJANA_global_radiation,LJUBLJANA_precipitation,LJUBLJANA_sunshine,LJUBLJANA_temp_mean,LJUBLJANA_temp_min,LJUBLJANA_temp_max,MAASTRICHT_cloud_cover,MAASTRICHT_wind_speed,MAASTRICHT_humidity,MAASTRICHT_pressure,MAASTRICHT_global_radiation,MAASTRICHT_precipitation,MAASTRICHT_sunshine,MAASTRICHT_temp_mean,MAASTRICHT_temp_min,MAASTRICHT_temp_max,MADRID_cloud_cover,MADRID_wind_speed,MADRID_humidity,MADRID_pressure,MADRID_global_radiation,MADRID_precipitation,MADRID_sunshine,MADRID_temp_mean,MADRID_temp_min,MADRID_temp_max,MUNCHENB_cloud_cover,MUNCHENB_humidity,MUNCHENB_global_radiation,MUNCHENB_precipitation,MUNCHENB_snow_depth,MUNCHENB_sunshine,MUNCHENB_temp_mean,MUNCHENB_temp_min,MUNCHENB_temp_max,OSLO_cloud_cover,OSLO_wind_speed,OSLO_humidity,OSLO_pressure,OSLO_global_radiation,OSLO_precipitation,OSLO_snow_depth,OSLO_sunshine,OSLO_temp_mean,OSLO_temp_min,OSLO_temp_max,ROMA_cloud_cover,ROMA_wind_speed,ROMA_humidity,ROMA_pressure,ROMA_sunshine,ROMA_temp_mean,SONNBLICK_cloud_cover,SONNBLICK_wind_speed,SONNBLICK_humidity,SONNBLICK_pressure,SONNBLICK_global_radiation,SONNBLICK_precipitation,SONNBLICK_sunshine,SONNBLICK_temp_mean,SONNBLICK_temp_min,SONNBLICK_temp_max,STOCKHOLM_cloud_cover,STOCKHOLM_pressure,STOCKHOLM_global_radiation,STOCKHOLM_precipitation,STOCKHOLM_sunshine,STOCKHOLM_temp_mean,STOCKHOLM_temp_min,STOCKHOLM_temp_max,TOURS_wind_speed,TOURS_humidity,TOURS_pressure,TOURS_global_radiation,TOURS_precipitation,TOURS_temp_mean,TOURS_temp_min,TOURS_temp_max,VALENTIA_cloud_cover,VALENTIA_humidity,VALENTIA_pressure,VALENTIA_global_radiation,VALENTIA_precipitation,VALENTIA_snow_depth,VALENTIA_sunshine,VALENTIA_temp_mean,VALENTIA_temp_min,VALENTIA_temp_max
0,19600101,1,7,2.1,0.85,1.018,0.32,0.09,0,0.7,6.5,0.8,10.9,1,0.81,1.0195,0.88,0.00,7.0,3.7,-0.9,7.9,4,0.67,1.017,0.44,0.01,2.3,2.4,-0.4,5.1,7,7.7,0.85,1.0032,0.07,0.25,0.0,9.3,7.4,11.0,8,5.4,0.83,1.0161,0.12,0.08,0,0.0,10.0,7.0,11.5,8,0.91,0.00,0,0.8,-0.3,1.6,7,0.91,1.0010,0.13,0.22,0,0.0,10.6,9.4,8.3,2.9,0.82,1.0094,0.28,0.48,1.6,7.9,3.9,9.4,8,1.4,1.00,1.0173,0.20,0.00,0.0,-0.6,-1.9,0.5,7,8.7,0.83,1.0063,0.22,0.32,1.0,9.5,8.5,11.1,6,0.0,0.92,1.0260,0.53,0.0,1.4,7.6,4.4,10.8,5,0.67,0.20,0.10,0,0.0,6.9,1.1,10.4,8,4.0,0.98,0.9978,0.04,1.14,0,0.0,4.9,3.8,5.9,3,2.6,0.73,1.0152,7.1,7.8,4,4.5,0.73,1.0304,0.48,0.01,2.3,-5.9,-8.5,-3.2,5,1.0114,0.05,0.32,0.0,4.2,2.2,4.9,3.8,0.76,1.0169,1.54,0.44,10.0,7.8,12.2,5,0.88,1.0003,0.45,0.34,0,4.7,8.5,6.0,10.9
1,19600102,1,6,2.1,0.84,1.018,0.36,1.05,0,1.1,6.1,3.3,10.1,6,0.84,1.0172,0.25,0.00,0.0,2.9,2.2,4.4,4,0.67,1.017,0.18,0.31,0.0,2.3,1.4,3.1,8,4.1,0.90,1.0056,0.14,0.06,0.1,7.7,6.4,8.3,8,3.6,0.89,1.0161,0.18,0.66,0,0.5,8.2,7.4,11.0,8,0.93,0.08,0,1.6,0.9,2.2,7,0.98,1.0051,0.13,0.23,0,0.0,6.1,3.9,10.6,1.9,0.86,1.0086,0.12,0.27,0.0,7.7,6.8,9.1,6,1.4,0.94,1.0173,0.56,0.13,3.2,2.1,-1.3,5.5,8,5.7,0.92,1.0062,0.17,1.34,0.4,8.6,7.5,9.9,7,0.8,0.86,1.0254,0.46,0.0,0.9,9.8,7.4,12.2,6,0.72,0.61,0.30,0,5.1,6.2,4.2,10.2,8,5.1,0.62,1.0139,0.04,0.00,0,0.0,3.4,2.8,4.9,3,2.6,0.73,1.0152,7.1,12.2,6,6.7,0.97,1.0292,0.21,0.61,0.0,-9.5,-10.5,-8.5,5,1.0114,0.05,0.06,0.0,4.0,3.0,5.0,3.8,0.76,1.0169,1.54,0.71,9.5,7.0,12.0,7,0.91,1.0007,0.25,0.84,0,0.7,8.9,5.6,12.1
2,19600103,1,8,2.1,0.90,1.018,0.18,0.30,0,0.0,8.5,5.1,9.9,6,0.77,1.0179,0.67,0.00,3.5,3.1,-0.5,6.4,4,0.67,1.017,0.30,0.00,0.6,2.7,1.7,5.3,6,3.1,0.92,1.0165,0.28,0.01,3.0,6.8,4.6,9.9,7,3.1,0.95,1.0161,0.12,0.07,0,0.0,7.1,6.9,9.1,8,0.94,0.15,0,0.7,0.4,1.7,8,0.96,1.0166,0.15,0.07,0,0.1,8.4,6.1,12.2,1.3,0.91,1.0129,0.12,0.60,0.0,6.5,6.0,8.0,8,1.4,0.96,1.0173,0.20,0.12,0.0,4.6,0.9,6.3,7,3.6,0.97,1.0167,0.12,0.46,0.0,6.9,5.5,9.9,5,1.9,0.90,1.0287,0.63,0.0,2.3,8.6,6.4,10.8,6,0.91,0.20,0.30,0,0.0,5.8,4.0,8.0,8,2.3,0.69,1.0234,0.04,0.08,0,0.0,1.9,0.6,3.1,3,2.6,0.73,1.0152,7.1,10.2,8,7.5,0.93,1.0320,0.21,3.20,0.0,-9.5,-10.0,-8.9,5,1.0114,0.05,0.02,0.0,2.4,1.3,4.1,3.8,0.76,1.0169,1.54,0.10,10.3,9.0,11.6,7,0.91,1.0096,0.17,0.08,0,0.1,10.5,8.1,12.9
3,19600104,1,3,2.1,0.92,1.018,0.58,0.00,0,4.1,6.3,3.8,10.6,8,0.93,1.0268,0.25,0.00,0.0,2.0,-2.0,3.0,4,0.67,1.017,0.19,0.00,0.0,2.0,0.4,4.4,8,5.7,0.95,1.0265,0.08,0.09,0.0,6.7,3.6,10.1,8,2.7,0.86,1.0161,0.12,0.02,0,0.0,6.8,3.6,8.0,7,0.91,0.00,0,-0.1,-0.9,2.0,8,0.98,1.0230,0.13,0.00,0,0.0,9.4,6.7,8.9,1.4,0.87,1.0290,0.12,0.00,0.0,5.8,5.2,6.5,6,1.4,0.94,1.0173,0.49,0.00,2.2,3.2,1.0,7.0,7,5.1,0.89,1.0277,0.16,0.00,0.3,7.0,3.0,10.0,0,1.1,0.75,1.0281,1.16,0.0,8.7,10.3,4.5,16.1,6,0.90,0.20,0.01,0,0.0,3.9,3.2,5.4,8,3.9,0.98,1.0244,0.04,0.35,0,0.0,3.0,0.4,4.9,3,2.6,0.73,1.0152,7.1,10.8,5,7.5,0.93,1.0443,0.22,1.10,0.0,-11.5,-12.9,-10.0,5,1.0114,0.05,0.00,0.0,1.2,0.4,2.3,3.8,0.76,1.0169,1.54,0.10,11.2,9.9,12.6,7,0.86,1.0184,0.13,0.98,0,0.0,7.4,7.3,10.6
4,19600105,1,6,2.1,0.95,1.018,0.65,0.14,0,5.4,3.0,-0.7,6.0,8,0.99,1.0286,0.25,0.06,0.0,2.0,0.7,2.8,4,0.67,1.017,0.19,0.00,0.0,2.5,1.1,5.3,6,6.7,0.90,1.0243,0.04,0.39,0.0,8.0,2.4,11.2,7,4.5,0.92,1.0161,0.12,0.62,0,0.0,7.7,6.2,11.0,7,0.94,0.17,0,0.4,-1.7,1.5,5,0.84,1.0275,0.30,0.00,0,2.1,8.9,8.9,7.2,2.9,0.86,1.0262,0.13,0.71,0.0,5.4,3.7,6.0,7,1.4,0.94,1.0173,0.20,0.00,0.0,3.6,0.4,4.8,7,6.2,0.92,1.0259,0.12,0.56,0.0,8.1,2.5,11.1,2,1.1,0.64,1.0269,1.10,0.0,7.8,12.1,8.2,16.0,5,0.85,0.65,0.96,0,5.6,1.8,-3.0,6.0,8,1.5,0.96,1.0092,0.05,0.26,0,0.0,3.7,2.9,4.9,3,2.6,0.73,1.0152,7.1,9.9,2,10.2,0.75,1.0430,0.72,0.01,6.1,-9.3,-12.0,-6.5,5,1.0114,0.05,1.32,0.0,3.3,0.8,4.3,3.8,0.76,1.0169,1.54,0.00,11.4,10.7,12.0,3,0.80,1.0328,0.46,0.00,0,5.7,5.7,3.0,8.4

In [5]:
# check shape
unscaled.shape

(22950, 170)

In [6]:
# check second dataset
prediction.head()

,DATE,BASEL_pleasant_weather,BELGRADE_pleasant_weather,BUDAPEST_pleasant_weather,DEBILT_pleasant_weather,DUSSELDORF_pleasant_weather,HEATHROW_pleasant_weather,KASSEL_pleasant_weather,LJUBLJANA_pleasant_weather,MAASTRICHT_pleasant_weather,MADRID_pleasant_weather,MUNCHENB_pleasant_weather,OSLO_pleasant_weather,SONNBLICK_pleasant_weather,STOCKHOLM_pleasant_weather,VALENTIA_pleasant_weather
0,19600101,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,19600102,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,19600103,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,19600104,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,19600105,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [7]:
prediction.shape

(22950, 16)

#### 2. Data Wrangling and Reshaping

In [8]:
# Remove weather stations not included in "pleasant weather" answers
unscaled = unscaled.drop(['GDANSK_cloud_cover', 'GDANSK_humidity', 'GDANSK_precipitation', 'GDANSK_snow_depth', 'GDANSK_temp_mean', 'GDANSK_temp_min', 'GDANSK_temp_max',
                        'ROMA_cloud_cover', 'ROMA_wind_speed', 'ROMA_humidity', 'ROMA_pressure', 'ROMA_sunshine', 'ROMA_temp_mean',
                        'TOURS_wind_speed', 'TOURS_humidity', 'TOURS_pressure', 'TOURS_global_radiation', 'TOURS_precipitation', 'TOURS_temp_mean', 'TOURS_temp_min', 'TOURS_temp_max'], axis=1)

In [9]:
# confirm drop
unscaled.shape

(22950, 149)

In [10]:
unscaled.head()

,DATE,MONTH,BASEL_cloud_cover,BASEL_wind_speed,BASEL_humidity,BASEL_pressure,BASEL_global_radiation,BASEL_precipitation,BASEL_snow_depth,BASEL_sunshine,BASEL_temp_mean,BASEL_temp_min,BASEL_temp_max,BELGRADE_cloud_cover,BELGRADE_humidity,BELGRADE_pressure,BELGRADE_global_radiation,BELGRADE_precipitation,BELGRADE_sunshine,BELGRADE_temp_mean,BELGRADE_temp_min,BELGRADE_temp_max,BUDAPEST_cloud_cover,BUDAPEST_humidity,BUDAPEST_pressure,BUDAPEST_global_radiation,BUDAPEST_precipitation,BUDAPEST_sunshine,BUDAPEST_temp_mean,BUDAPEST_temp_min,BUDAPEST_temp_max,DEBILT_cloud_cover,DEBILT_wind_speed,DEBILT_humidity,DEBILT_pressure,DEBILT_global_radiation,DEBILT_precipitation,DEBILT_sunshine,DEBILT_temp_mean,DEBILT_temp_min,DEBILT_temp_max,DUSSELDORF_cloud_cover,DUSSELDORF_wind_speed,DUSSELDORF_humidity,DUSSELDORF_pressure,DUSSELDORF_global_radiation,DUSSELDORF_precipitation,DUSSELDORF_snow_depth,DUSSELDORF_sunshine,DUSSELDORF_temp_mean,DUSSELDORF_temp_min,DUSSELDORF_temp_max,HEATHROW_cloud_cover,HEATHROW_humidity,HEATHROW_pressure,HEATHROW_global_radiation,HEATHROW_precipitation,HEATHROW_snow_depth,HEATHROW_sunshine,HEATHROW_temp_mean,HEATHROW_temp_min,HEATHROW_temp_max,KASSEL_wind_speed,KASSEL_humidity,KASSEL_pressure,KASSEL_global_radiation,KASSEL_precipitation,KASSEL_sunshine,KASSEL_temp_mean,KASSEL_temp_min,KASSEL_temp_max,LJUBLJANA_cloud_cover,LJUBLJANA_wind_speed,LJUBLJANA_humidity,LJUBLJANA_pressure,LJUBLJANA_global_radiation,LJUBLJANA_precipitation,LJUBLJANA_sunshine,LJUBLJANA_temp_mean,LJUBLJANA_temp_min,LJUBLJANA_temp_max,MAASTRICHT_cloud_cover,MAASTRICHT_wind_speed,MAASTRICHT_humidity,MAASTRICHT_pressure,MAASTRICHT_global_radiation,MAASTRICHT_precipitation,MAASTRICHT_sunshine,MAASTRICHT_temp_mean,MAASTRICHT_temp_min,MAASTRICHT_temp_max,MADRID_cloud_cover,MADRID_wind_speed,MADRID_humidity,MADRID_pressure,MADRID_global_radiation,MADRID_precipitation,MADRID_sunshine,MADRID_temp_mean,MADRID_temp_min,MADRID_temp_max,MUNCHENB_cloud_cover,MUNCHENB_humidity,MUNCHENB_global_radiation,MUNCHENB_precipitation,MUNCHENB_snow_depth,MUNCHENB_sunshine,MUNCHENB_temp_mean,MUNCHENB_temp_min,MUNCHENB_temp_max,OSLO_cloud_cover,OSLO_wind_speed,OSLO_humidity,OSLO_pressure,OSLO_global_radiation,OSLO_precipitation,OSLO_snow_depth,OSLO_sunshine,OSLO_temp_mean,OSLO_temp_min,OSLO_temp_max,SONNBLICK_cloud_cover,SONNBLICK_wind_speed,SONNBLICK_humidity,SONNBLICK_pressure,SONNBLICK_global_radiation,SONNBLICK_precipitation,SONNBLICK_sunshine,SONNBLICK_temp_mean,SONNBLICK_temp_min,SONNBLICK_temp_max,STOCKHOLM_cloud_cover,STOCKHOLM_pressure,STOCKHOLM_global_radiation,STOCKHOLM_precipitation,STOCKHOLM_sunshine,STOCKHOLM_temp_mean,STOCKHOLM_temp_min,STOCKHOLM_temp_max,VALENTIA_cloud_cover,VALENTIA_humidity,VALENTIA_pressure,VALENTIA_global_radiation,VALENTIA_precipitation,VALENTIA_snow_depth,VALENTIA_sunshine,VALENTIA_temp_mean,VALENTIA_temp_min,VALENTIA_temp_max
0,19600101,1,7,2.1,0.85,1.018,0.32,0.09,0,0.7,6.5,0.8,10.9,1,0.81,1.0195,0.88,0.00,7.0,3.7,-0.9,7.9,4,0.67,1.017,0.44,0.01,2.3,2.4,-0.4,5.1,7,7.7,0.85,1.0032,0.07,0.25,0.0,9.3,7.4,11.0,8,5.4,0.83,1.0161,0.12,0.08,0,0.0,10.0,7.0,11.5,7,0.91,1.0010,0.13,0.22,0,0.0,10.6,9.4,8.3,2.9,0.82,1.0094,0.28,0.48,1.6,7.9,3.9,9.4,8,1.4,1.00,1.0173,0.20,0.00,0.0,-0.6,-1.9,0.5,7,8.7,0.83,1.0063,0.22,0.32,1.0,9.5,8.5,11.1,6,0.0,0.92,1.0260,0.53,0.0,1.4,7.6,4.4,10.8,5,0.67,0.20,0.10,0,0.0,6.9,1.1,10.4,8,4.0,0.98,0.9978,0.04,1.14,0,0.0,4.9,3.8,5.9,4,4.5,0.73,1.0304,0.48,0.01,2.3,-5.9,-8.5,-3.2,5,1.0114,0.05,0.32,0.0,4.2,2.2,4.9,5,0.88,1.0003,0.45,0.34,0,4.7,8.5,6.0,10.9
1,19600102,1,6,2.1,0.84,1.018,0.36,1.05,0,1.1,6.1,3.3,10.1,6,0.84,1.0172,0.25,0.00,0.0,2.9,2.2,4.4,4,0.67,1.017,0.18,0.31,0.0,2.3,1.4,3.1,8,4.1,0.90,1.0056,0.14,0.06,0.1,7.7,6.4,8.3,8,3.6,0.89,1.0161,0.18,0.66,0,0.5,8.2,7.4,11.0,7,0.98,1.0051,0.13,0.23,0,0.0,6.1,3.9,10.6,1.9,0.86,1.0086,0.12,0.27,0.0,7.7,6.8,9.1,6,1.4,0.94,1.0173,0.56,0.13,3.2,2.1,-1.3,5.5,8,5.7,0.92,1.0062,0.17,1.34,0.4,8.6,7.5,9.9,7,0.8,0.86,1.0254,0.46,0.0,0.9,9.8,7.4,12.2,6,0.72,0.61,0.30,0,5.1,6.2,4.2,10.2,8,5.1,0.62,1.0139,0.04,0.00,0,0.0,3.4,2.8,4.9,6,6.7,0.97,1.0292,0.21,0.61,0.0,-9.5,-10.5,-8.5,5,1.0114,0.05,0.06,0.0,4.0,3.0,5.0,7,0.91,1.0007,0.25,0.84,0,0.7,8.9,5.6,12.1
2,19600103,1,8,2.1,0.90,1.018,0.18,0.30,0,0.0,8.5,5.1,9.9,6,0.77,1.0179,0.67,0.00,3.5,3.1,-0.5,6.4,4,0.67,1.017,0.30,0.00,0.6,2.7,1.7,5.3,6,3.1,0.92,1.0165,0.28,0.01,3.0,6.8,4.6,9.9,7,3.1,0.95,1.0161,0.12,0.07,0,0.0,7.1,6.9,9.1,8,0.96,1.0166,0.15,0.07,0,0.1,8.4,6.1,12.2,1.3,0.91,1.0129,0.12,0.60,0.0,6.5,6.0,8.0,8,1.4,0.96,1.0173,0.20,0.12,0.0,4.6,0.9,6.3,7,3.6,0.97,1.0167,0.12,0.46,0.0,6.9,5.5,9.9,5,1.9,0.90,1.0287,0.63,0.0,2.3,8.6,6.4,10.8,6,0.91,0.20,0.30,0,0.0,5.8,4.0,8.0,8,2.3,0.69,1.0234,0.04,0.08,0,0.0,1.9,0.6,3.1,8,7.5,0.93,1.0320,0.21,3.20,0.0,-9.5,-10.0,-8.9,5,1.0114,0.05,0.02,0.0,2.4,1.3,4.1,7,0.91,1.0096,0.17,0.08,0,0.1,10.5,8.1,12.9
3,19600104,1,3,2.1,0.92,1.018,0.58,0.00,0,4.1,6.3,3.8,10.6,8,0.93,1.0268,0.25,0.00,0.0,2.0,-2.0,3.0,4,0.67,1.017,0.19,0.00,0.0,2.0,0.4,4.4,8,5.7,0.95,1.0265,0.08,0.09,0.0,6.7,3.6,10.1,8,2.7,0.86,1.0161,0.12,0.02,0,0.0,6.8,3.6,8.0,8,0.98,1.0230,0.13,0.00,0,0.0,9.4,6.7,8.9,1.4,0.87,1.0290,0.12,0.00,0.0,5.8,5.2,6.5,6,1.4,0.94,1.0173,0.49,0.00,2.2,3.2,1.0,7.0,7,5.1,0.89,1.0277,0.16,0.00,0.3,7.0,3.0,10.0,0,1.1,0.75,1.0281,1.16,0.0,8.7,10.3,4.5,16.1,6,0.90,0.20,0.01,0,0.0,3.9,3.2,5.4,8,3.9,0.98,1.0244,0.04,0.35,0,0.0,3.0,0.4,4.9,5,7.5,0.93,1.0443,0.22,1.10,0.0,-11.5,-12.9,-10.0,5,1.0114,0.05,0.00,0.0,1.2,0.4,2.3,7,0.86,1.0184,0.13,0.98,0,0.0,7.4,7.3,10.6
4,19600105,1,6,2.1,0.95,1.018,0.65,0.14,0,5.4,3.0,-0.7,6.0,8,0.99,1.0286,0.25,0.06,0.0,2.0,0.7,2.8,4,0.67,1.017,0.19,0.00,0.0,2.5,1.1,5.3,6,6.7,0.90,1.0243,0.04,0.39,0.0,8.0,2.4,11.2,7,4.5,0.92,1.0161,0.12,0.62,0,0.0,7.7,6.2,11.0,5,0.84,1.0275,0.30,0.00,0,2.1,8.9,8.9,7.2,2.9,0.86,1.0262,0.13,0.71,0.0,5.4,3.7,6.0,7,1.4,0.94,1.0173,0.20,0.00,0.0,3.6,0.4,4.8,7,6.2,0.92,1.0259,0.12,0.56,0.0,8.1,2.5,11.1,2,1.1,0.64,1.0269,1.10,0.0,7.8,12.1,8.2,16.0,5,0.85,0.65,0.96,0,5.6,1.8,-3.0,6.0,8,1.5,0.96,1.0092,0.05,0.26,0,0.0,3.7,2.9,4.9,2,10.2,0.75,1.0430,0.72,0.01,6.1,-9.3,-12.0,-6.5,5,1.0114,0.05,1.32,0.0,3.3,0.8,4.3,3,0.80,1.0328,0.46,0.00,0,5.7,5.7,3.0,8.4

In [11]:
unscaled.isnull().sum()

DATE                           0
MONTH                          0
BASEL_cloud_cover              0
BASEL_wind_speed               0
BASEL_humidity                 0
BASEL_pressure                 0
BASEL_global_radiation         0
BASEL_precipitation            0
BASEL_snow_depth               0
BASEL_sunshine                 0
BASEL_temp_mean                0
BASEL_temp_min                 0
BASEL_temp_max                 0
BELGRADE_cloud_cover           0
BELGRADE_humidity              0
BELGRADE_pressure              0
BELGRADE_global_radiation      0
BELGRADE_precipitation         0
BELGRADE_sunshine              0
BELGRADE_temp_mean             0
BELGRADE_temp_min              0
BELGRADE_temp_max              0
BUDAPEST_cloud_cover           0
BUDAPEST_humidity              0
BUDAPEST_pressure              0
BUDAPEST_global_radiation      0
BUDAPEST_precipitation         0
BUDAPEST_sunshine              0
BUDAPEST_temp_mean             0
BUDAPEST_temp_min              0
BUDAPEST_temp_max              0
DEBILT_cloud_cover             0
DEBILT_wind_speed              0
DEBILT_humidity                0
DEBILT_pressure                0
DEBILT_global_radiation        0
DEBILT_precipitation           0
DEBILT_sunshine                0
DEBILT_temp_mean               0
DEBILT_temp_min                0
DEBILT_temp_max                0
DUSSELDORF_cloud_cover         0
DUSSELDORF_wind_speed          0
DUSSELDORF_humidity            0
DUSSELDORF_pressure            0
DUSSELDORF_global_radiation    0
DUSSELDORF_precipitation       0
DUSSELDORF_snow_depth          0
DUSSELDORF_sunshine            0
DUSSELDORF_temp_mean           0
DUSSELDORF_temp_min            0
DUSSELDORF_temp_max            0
HEATHROW_cloud_cover           0
HEATHROW_humidity              0
HEATHROW_pressure              0
HEATHROW_global_radiation      0
HEATHROW_precipitation         0
HEATHROW_snow_depth            0
HEATHROW_sunshine              0
HEATHROW_temp_mean             0
HEATHROW_temp_min              0
HEATHROW_temp_max              0
KASSEL_wind_speed              0
KASSEL_humidity                0
KASSEL_pressure                0
KASSEL_global_radiation        0
KASSEL_precipitation           0
KASSEL_sunshine                0
KASSEL_temp_mean               0
KASSEL_temp_min                0
KASSEL_temp_max                0
LJUBLJANA_cloud_cover          0
LJUBLJANA_wind_speed           0
LJUBLJANA_humidity             0
LJUBLJANA_pressure             0
LJUBLJANA_global_radiation     0
LJUBLJANA_precipitation        0
LJUBLJANA_sunshine             0
LJUBLJANA_temp_mean            0
LJUBLJANA_temp_min             0
LJUBLJANA_temp_max             0
MAASTRICHT_cloud_cover         0
MAASTRICHT_wind_speed          0
MAASTRICHT_humidity            0
MAASTRICHT_pressure            0
MAASTRICHT_global_radiation    0
MAASTRICHT_precipitation       0
MAASTRICHT_sunshine            0
MAASTRICHT_temp_mean           0
MAASTRICHT_temp_min            0
MAASTRICHT_temp_max            0
MADRID_cloud_cover             0
MADRID_wind_speed              0
MADRID_humidity                0
MADRID_pressure                0
MADRID_global_radiation        0
MADRID_precipitation           0
MADRID_sunshine                0
MADRID_temp_mean               0
MADRID_temp_min                0
MADRID_temp_max                0
MUNCHENB_cloud_cover           0
MUNCHENB_humidity              0
MUNCHENB_global_radiation      0
MUNCHENB_precipitation         0
MUNCHENB_snow_depth            0
MUNCHENB_sunshine              0
MUNCHENB_temp_mean             0
MUNCHENB_temp_min              0
MUNCHENB_temp_max              0
OSLO_cloud_cover               0
OSLO_wind_speed                0
OSLO_humidity                  0
OSLO_pressure                  0
OSLO_global_radiation          0
OSLO_precipitation             0
OSLO_snow_depth                0
OSLO_sunshine                  0
OSLO_temp_mean                 0
OSLO_temp_min                  0
OSLO_temp_max                  0
SONNBLICK_cloud_cover          0
SONNBLICK_wind_speed           0
SONNBLICK_humidity             0
SONNBLICK_pressure             0
SONNBLICK_global_radiation     0
SONNBLICK_precipitation        0
SONNBLICK_sunshine             0
SONNBLICK_temp_mean            0
SONNBLICK_temp_min             0
SONNBLICK_temp_max             0
STOCKHOLM_cloud_cover          0
STOCKHOLM_pressure             0
STOCKHOLM_global_radiation     0
STOCKHOLM_precipitation        0
STOCKHOLM_sunshine             0
STOCKHOLM_temp_mean            0
STOCKHOLM_temp_min             0
STOCKHOLM_temp_max             0
VALENTIA_cloud_cover           0
VALENTIA_humidity              0
VALENTIA_pressure              0
VALENTIA_global_radiation      0
VALENTIA_precipitation         0
VALENTIA_snow_depth            0
VALENTIA_sunshine              0
VALENTIA_temp_mean             0
VALENTIA_temp_min              0
VALENTIA_temp_max              0
dtype: int64

In [12]:
# Extract the different observation types

observation_types = ['cloud_cover', 'wind_speed', 'humidity', 'pressure',
                     'global_radiation', 'precipitation', 'snow_depth', 
                     'sunshine', 'temp_mean', 'temp_min', 'temp_max']

In [13]:
# Create a dictionary to store the count of stations for each observation type
station_counts = {}

for obs in observation_types:
    # Select columns related to the current observation type
    columns = [col for col in unscaled.columns if col.endswith(obs)]
    
    # Count the number of stations (i.e., the number of columns) for the current observation type
    station_counts[obs] = len(columns)

# Print the count of stations for each observation type
print("Number of stations covered by each observation type:")
for obs, count in station_counts.items():
    print(f"{obs}: {count} stations")

Number of stations covered by each observation type:
cloud_cover: 14 stations
wind_speed: 9 stations
humidity: 14 stations
pressure: 14 stations
global_radiation: 15 stations
precipitation: 15 stations
snow_depth: 6 stations
sunshine: 15 stations
temp_mean: 15 stations
temp_min: 15 stations
temp_max: 15 stations

##### The Wind_speed and Snow_depth columns contain multiple missing values, so they will be removed.

In [14]:
# Get a list of columns containing 'wind_speed' or 'snow_depth'
cols_to_drop = [col for col in unscaled.columns if '_wind_speed' in col or '_snow_depth' in col]

# Drop the columns
unscaled = unscaled.drop(cols_to_drop, axis=1)

In [15]:
unscaled.shape # Expecation is to have 15 columns less

(22950, 134)

##### There is one missing entry in each of the following columns across multiple observations: cloud_cover, humidity, and pressure.

In [16]:
# Find the stations with the above entries missing
# Get all column names
all_columns = unscaled.columns.tolist()
# Exclude 'DATE' and 'MONTH' columns
all_columns = [col for col in all_columns if col not in ['DATE', 'MONTH']]  
# Extract unique weather station names
weather_stations = set()  # Use a set to automatically store only unique values
for col in all_columns:
    station_name = col.split('_')[0]  # Split the column name at the underscore and take the first part
    weather_stations.add(station_name)

# Print the list of weather stations
print(weather_stations)

{'HEATHROW', 'LJUBLJANA', 'OSLO', 'KASSEL', 'VALENTIA', 'MUNCHENB', 'STOCKHOLM', 'DEBILT', 'MAASTRICHT', 'BELGRADE', 'BUDAPEST', 'MADRID', 'BASEL', 'DUSSELDORF', 'SONNBLICK'}

In [17]:
# Find stations missing observation types
observation_types = ['cloud_cover', 'humidity', 'pressure']

missing_stations_by_observation = {}

for obs in observation_types:
    # Select columns related to the current observation type
    columns = [col for col in unscaled.columns if col.endswith(obs)]
    
    # Extract station names by removing the observation type from the column names
    station_names = set([col.replace(f'_{obs}', '') for col in columns])
    
    # Identify stations that are in all_stations but missing from the current observation type
    missing_stations = weather_stations - station_names
    
    # Store the missing station names in the dictionary
    missing_stations_by_observation[obs] = missing_stations

# Print the missing station names for each observation type
for obs, missing_stations in missing_stations_by_observation.items():
    print(f"\nStations missing from {obs}:")
    if missing_stations:
        for station in missing_stations:
            print(station)
    else:
        print("None")

Stations missing from cloud_cover:
KASSEL

Stations missing from humidity:
STOCKHOLM

Stations missing from pressure:
MUNCHENB

In [18]:
unscaled.head()

,DATE,MONTH,BASEL_cloud_cover,BASEL_humidity,BASEL_pressure,BASEL_global_radiation,BASEL_precipitation,BASEL_sunshine,BASEL_temp_mean,BASEL_temp_min,BASEL_temp_max,BELGRADE_cloud_cover,BELGRADE_humidity,BELGRADE_pressure,BELGRADE_global_radiation,BELGRADE_precipitation,BELGRADE_sunshine,BELGRADE_temp_mean,BELGRADE_temp_min,BELGRADE_temp_max,BUDAPEST_cloud_cover,BUDAPEST_humidity,BUDAPEST_pressure,BUDAPEST_global_radiation,BUDAPEST_precipitation,BUDAPEST_sunshine,BUDAPEST_temp_mean,BUDAPEST_temp_min,BUDAPEST_temp_max,DEBILT_cloud_cover,DEBILT_humidity,DEBILT_pressure,DEBILT_global_radiation,DEBILT_precipitation,DEBILT_sunshine,DEBILT_temp_mean,DEBILT_temp_min,DEBILT_temp_max,DUSSELDORF_cloud_cover,DUSSELDORF_humidity,DUSSELDORF_pressure,DUSSELDORF_global_radiation,DUSSELDORF_precipitation,DUSSELDORF_sunshine,DUSSELDORF_temp_mean,DUSSELDORF_temp_min,DUSSELDORF_temp_max,HEATHROW_cloud_cover,HEATHROW_humidity,HEATHROW_pressure,HEATHROW_global_radiation,HEATHROW_precipitation,HEATHROW_sunshine,HEATHROW_temp_mean,HEATHROW_temp_min,HEATHROW_temp_max,KASSEL_humidity,KASSEL_pressure,KASSEL_global_radiation,KASSEL_precipitation,KASSEL_sunshine,KASSEL_temp_mean,KASSEL_temp_min,KASSEL_temp_max,LJUBLJANA_cloud_cover,LJUBLJANA_humidity,LJUBLJANA_pressure,LJUBLJANA_global_radiation,LJUBLJANA_precipitation,LJUBLJANA_sunshine,LJUBLJANA_temp_mean,LJUBLJANA_temp_min,LJUBLJANA_temp_max,MAASTRICHT_cloud_cover,MAASTRICHT_humidity,MAASTRICHT_pressure,MAASTRICHT_global_radiation,MAASTRICHT_precipitation,MAASTRICHT_sunshine,MAASTRICHT_temp_mean,MAASTRICHT_temp_min,MAASTRICHT_temp_max,MADRID_cloud_cover,MADRID_humidity,MADRID_pressure,MADRID_global_radiation,MADRID_precipitation,MADRID_sunshine,MADRID_temp_mean,MADRID_temp_min,MADRID_temp_max,MUNCHENB_cloud_cover,MUNCHENB_humidity,MUNCHENB_global_radiation,MUNCHENB_precipitation,MUNCHENB_sunshine,MUNCHENB_temp_mean,MUNCHENB_temp_min,MUNCHENB_temp_max,OSLO_cloud_cover,OSLO_humidity,OSLO_pressure,OSLO_global_radiation,OSLO_precipitation,OSLO_sunshine,OSLO_temp_mean,OSLO_temp_min,OSLO_temp_max,SONNBLICK_cloud_cover,SONNBLICK_humidity,SONNBLICK_pressure,SONNBLICK_global_radiation,SONNBLICK_precipitation,SONNBLICK_sunshine,SONNBLICK_temp_mean,SONNBLICK_temp_min,SONNBLICK_temp_max,STOCKHOLM_cloud_cover,STOCKHOLM_pressure,STOCKHOLM_global_radiation,STOCKHOLM_precipitation,STOCKHOLM_sunshine,STOCKHOLM_temp_mean,STOCKHOLM_temp_min,STOCKHOLM_temp_max,VALENTIA_cloud_cover,VALENTIA_humidity,VALENTIA_pressure,VALENTIA_global_radiation,VALENTIA_precipitation,VALENTIA_sunshine,VALENTIA_temp_mean,VALENTIA_temp_min,VALENTIA_temp_max
0,19600101,1,7,0.85,1.018,0.32,0.09,0.7,6.5,0.8,10.9,1,0.81,1.0195,0.88,0.00,7.0,3.7,-0.9,7.9,4,0.67,1.017,0.44,0.01,2.3,2.4,-0.4,5.1,7,0.85,1.0032,0.07,0.25,0.0,9.3,7.4,11.0,8,0.83,1.0161,0.12,0.08,0.0,10.0,7.0,11.5,7,0.91,1.0010,0.13,0.22,0.0,10.6,9.4,8.3,0.82,1.0094,0.28,0.48,1.6,7.9,3.9,9.4,8,1.00,1.0173,0.20,0.00,0.0,-0.6,-1.9,0.5,7,0.83,1.0063,0.22,0.32,1.0,9.5,8.5,11.1,6,0.92,1.0260,0.53,0.0,1.4,7.6,4.4,10.8,5,0.67,0.20,0.10,0.0,6.9,1.1,10.4,8,0.98,0.9978,0.04,1.14,0.0,4.9,3.8,5.9,4,0.73,1.0304,0.48,0.01,2.3,-5.9,-8.5,-3.2,5,1.0114,0.05,0.32,0.0,4.2,2.2,4.9,5,0.88,1.0003,0.45,0.34,4.7,8.5,6.0,10.9
1,19600102,1,6,0.84,1.018,0.36,1.05,1.1,6.1,3.3,10.1,6,0.84,1.0172,0.25,0.00,0.0,2.9,2.2,4.4,4,0.67,1.017,0.18,0.31,0.0,2.3,1.4,3.1,8,0.90,1.0056,0.14,0.06,0.1,7.7,6.4,8.3,8,0.89,1.0161,0.18,0.66,0.5,8.2,7.4,11.0,7,0.98,1.0051,0.13,0.23,0.0,6.1,3.9,10.6,0.86,1.0086,0.12,0.27,0.0,7.7,6.8,9.1,6,0.94,1.0173,0.56,0.13,3.2,2.1,-1.3,5.5,8,0.92,1.0062,0.17,1.34,0.4,8.6,7.5,9.9,7,0.86,1.0254,0.46,0.0,0.9,9.8,7.4,12.2,6,0.72,0.61,0.30,5.1,6.2,4.2,10.2,8,0.62,1.0139,0.04,0.00,0.0,3.4,2.8,4.9,6,0.97,1.0292,0.21,0.61,0.0,-9.5,-10.5,-8.5,5,1.0114,0.05,0.06,0.0,4.0,3.0,5.0,7,0.91,1.0007,0.25,0.84,0.7,8.9,5.6,12.1
2,19600103,1,8,0.90,1.018,0.18,0.30,0.0,8.5,5.1,9.9,6,0.77,1.0179,0.67,0.00,3.5,3.1,-0.5,6.4,4,0.67,1.017,0.30,0.00,0.6,2.7,1.7,5.3,6,0.92,1.0165,0.28,0.01,3.0,6.8,4.6,9.9,7,0.95,1.0161,0.12,0.07,0.0,7.1,6.9,9.1,8,0.96,1.0166,0.15,0.07,0.1,8.4,6.1,12.2,0.91,1.0129,0.12,0.60,0.0,6.5,6.0,8.0,8,0.96,1.0173,0.20,0.12,0.0,4.6,0.9,6.3,7,0.97,1.0167,0.12,0.46,0.0,6.9,5.5,9.9,5,0.90,1.0287,0.63,0.0,2.3,8.6,6.4,10.8,6,0.91,0.20,0.30,0.0,5.8,4.0,8.0,8,0.69,1.0234,0.04,0.08,0.0,1.9,0.6,3.1,8,0.93,1.0320,0.21,3.20,0.0,-9.5,-10.0,-8.9,5,1.0114,0.05,0.02,0.0,2.4,1.3,4.1,7,0.91,1.0096,0.17,0.08,0.1,10.5,8.1,12.9
3,19600104,1,3,0.92,1.018,0.58,0.00,4.1,6.3,3.8,10.6,8,0.93,1.0268,0.25,0.00,0.0,2.0,-2.0,3.0,4,0.67,1.017,0.19,0.00,0.0,2.0,0.4,4.4,8,0.95,1.0265,0.08,0.09,0.0,6.7,3.6,10.1,8,0.86,1.0161,0.12,0.02,0.0,6.8,3.6,8.0,8,0.98,1.0230,0.13,0.00,0.0,9.4,6.7,8.9,0.87,1.0290,0.12,0.00,0.0,5.8,5.2,6.5,6,0.94,1.0173,0.49,0.00,2.2,3.2,1.0,7.0,7,0.89,1.0277,0.16,0.00,0.3,7.0,3.0,10.0,0,0.75,1.0281,1.16,0.0,8.7,10.3,4.5,16.1,6,0.90,0.20,0.01,0.0,3.9,3.2,5.4,8,0.98,1.0244,0.04,0.35,0.0,3.0,0.4,4.9,5,0.93,1.0443,0.22,1.10,0.0,-11.5,-12.9,-10.0,5,1.0114,0.05,0.00,0.0,1.2,0.4,2.3,7,0.86,1.0184,0.13,0.98,0.0,7.4,7.3,10.6
4,19600105,1,6,0.95,1.018,0.65,0.14,5.4,3.0,-0.7,6.0,8,0.99,1.0286,0.25,0.06,0.0,2.0,0.7,2.8,4,0.67,1.017,0.19,0.00,0.0,2.5,1.1,5.3,6,0.90,1.0243,0.04,0.39,0.0,8.0,2.4,11.2,7,0.92,1.0161,0.12,0.62,0.0,7.7,6.2,11.0,5,0.84,1.0275,0.30,0.00,2.1,8.9,8.9,7.2,0.86,1.0262,0.13,0.71,0.0,5.4,3.7,6.0,7,0.94,1.0173,0.20,0.00,0.0,3.6,0.4,4.8,7,0.92,1.0259,0.12,0.56,0.0,8.1,2.5,11.1,2,0.64,1.0269,1.10,0.0,7.8,12.1,8.2,16.0,5,0.85,0.65,0.96,5.6,1.8,-3.0,6.0,8,0.96,1.0092,0.05,0.26,0.0,3.7,2.9,4.9,2,0.75,1.0430,0.72,0.01,6.1,-9.3,-12.0,-6.5,5,1.0114,0.05,1.32,0.0,3.3,0.8,4.3,3,0.80,1.0328,0.46,0.00,5.7,5.7,3.0,8.4

In [19]:
# Cloud cover is the start of a stations data, Kassel is next to Heathrow, find the position of Heathrow_temp_max for the insertion of Kassel_cloud_cover
unscaled.columns.get_loc('HEATHROW_temp_max')

55

In [20]:
# Find the position for insertion of Stockholm humidity
unscaled.columns.get_loc('STOCKHOLM_cloud_cover') #humidity is 1 after cloud cover so (result +1)

117

In [21]:
# Find position for Munchenb pressure
unscaled.columns.get_loc('MUNCHENB_cloud_cover') # pressure is 2 after cloud cover so (result +2)

91

In [22]:
# Insert new columns into "unscaled" at specific positions.
# The data for these new columns is taken from weather stations they are close to

unscaled.insert(56,'KASSEL_cloud_cover', unscaled['DUSSELDORF_cloud_cover'])
unscaled.insert(119, 'STOCKHOLM_humidity', unscaled['OSLO_humidity'])
unscaled.insert(94,'MUNCHENB_pressure',unscaled['BASEL_pressure'])

In [23]:
unscaled.columns.tolist()

['DATE',
 'MONTH',
 'BASEL_cloud_cover',
 'BASEL_humidity',
 'BASEL_pressure',
 'BASEL_global_radiation',
 'BASEL_precipitation',
 'BASEL_sunshine',
 'BASEL_temp_mean',
 'BASEL_temp_min',
 'BASEL_temp_max',
 'BELGRADE_cloud_cover',
 'BELGRADE_humidity',
 'BELGRADE_pressure',
 'BELGRADE_global_radiation',
 'BELGRADE_precipitation',
 'BELGRADE_sunshine',
 'BELGRADE_temp_mean',
 'BELGRADE_temp_min',
 'BELGRADE_temp_max',
 'BUDAPEST_cloud_cover',
 'BUDAPEST_humidity',
 'BUDAPEST_pressure',
 'BUDAPEST_global_radiation',
 'BUDAPEST_precipitation',
 'BUDAPEST_sunshine',
 'BUDAPEST_temp_mean',
 'BUDAPEST_temp_min',
 'BUDAPEST_temp_max',
 'DEBILT_cloud_cover',
 'DEBILT_humidity',
 'DEBILT_pressure',
 'DEBILT_global_radiation',
 'DEBILT_precipitation',
 'DEBILT_sunshine',
 'DEBILT_temp_mean',
 'DEBILT_temp_min',
 'DEBILT_temp_max',
 'DUSSELDORF_cloud_cover',
 'DUSSELDORF_humidity',
 'DUSSELDORF_pressure',
 'DUSSELDORF_global_radiation',
 'DUSSELDORF_precipitation',
 'DUSSELDORF_sunshine',
 'DUSSELDORF_temp_mean',
 'DUSSELDORF_temp_min',
 'DUSSELDORF_temp_max',
 'HEATHROW_cloud_cover',
 'HEATHROW_humidity',
 'HEATHROW_pressure',
 'HEATHROW_global_radiation',
 'HEATHROW_precipitation',
 'HEATHROW_sunshine',
 'HEATHROW_temp_mean',
 'HEATHROW_temp_min',
 'HEATHROW_temp_max',
 'KASSEL_cloud_cover',
 'KASSEL_humidity',
 'KASSEL_pressure',
 'KASSEL_global_radiation',
 'KASSEL_precipitation',
 'KASSEL_sunshine',
 'KASSEL_temp_mean',
 'KASSEL_temp_min',
 'KASSEL_temp_max',
 'LJUBLJANA_cloud_cover',
 'LJUBLJANA_humidity',
 'LJUBLJANA_pressure',
 'LJUBLJANA_global_radiation',
 'LJUBLJANA_precipitation',
 'LJUBLJANA_sunshine',
 'LJUBLJANA_temp_mean',
 'LJUBLJANA_temp_min',
 'LJUBLJANA_temp_max',
 'MAASTRICHT_cloud_cover',
 'MAASTRICHT_humidity',
 'MAASTRICHT_pressure',
 'MAASTRICHT_global_radiation',
 'MAASTRICHT_precipitation',
 'MAASTRICHT_sunshine',
 'MAASTRICHT_temp_mean',
 'MAASTRICHT_temp_min',
 'MAASTRICHT_temp_max',
 'MADRID_cloud_cover',
 'MADRID_humidity',
 'MADRID_pressure',
 'MADRID_global_radiation',
 'MADRID_precipitation',
 'MADRID_sunshine',
 'MADRID_temp_mean',
 'MADRID_temp_min',
 'MADRID_temp_max',
 'MUNCHENB_cloud_cover',
 'MUNCHENB_humidity',
 'MUNCHENB_pressure',
 'MUNCHENB_global_radiation',
 'MUNCHENB_precipitation',
 'MUNCHENB_sunshine',
 'MUNCHENB_temp_mean',
 'MUNCHENB_temp_min',
 'MUNCHENB_temp_max',
 'OSLO_cloud_cover',
 'OSLO_humidity',
 'OSLO_pressure',
 'OSLO_global_radiation',
 'OSLO_precipitation',
 'OSLO_sunshine',
 'OSLO_temp_mean',
 'OSLO_temp_min',
 'OSLO_temp_max',
 'SONNBLICK_cloud_cover',
 'SONNBLICK_humidity',
 'SONNBLICK_pressure',
 'SONNBLICK_global_radiation',
 'SONNBLICK_precipitation',
 'SONNBLICK_sunshine',
 'SONNBLICK_temp_mean',
 'SONNBLICK_temp_min',
 'SONNBLICK_temp_max',
 'STOCKHOLM_cloud_cover',
 'STOCKHOLM_humidity',
 'STOCKHOLM_pressure',
 'STOCKHOLM_global_radiation',
 'STOCKHOLM_precipitation',
 'STOCKHOLM_sunshine',
 'STOCKHOLM_temp_mean',
 'STOCKHOLM_temp_min',
 'STOCKHOLM_temp_max',
 'VALENTIA_cloud_cover',
 'VALENTIA_humidity',
 'VALENTIA_pressure',
 'VALENTIA_global_radiation',
 'VALENTIA_precipitation',
 'VALENTIA_sunshine',
 'VALENTIA_temp_mean',
 'VALENTIA_temp_min',
 'VALENTIA_temp_max']

In [24]:
unscaled.shape

(22950, 137)

In [25]:
# Export cleaned dataset
unscaled.to_csv(os.path.join(path, '02 Data', 'Prepared Data', 'weather_cleaned.csv'), index=False)

In [28]:
# Drop unnecessary columns
unscaled.drop(['DATE', 'MONTH'], axis=1, inplace=True)

In [29]:
# confirm drop
unscaled.shape

(22950, 135)

In [30]:
prediction.head()

,DATE,BASEL_pleasant_weather,BELGRADE_pleasant_weather,BUDAPEST_pleasant_weather,DEBILT_pleasant_weather,DUSSELDORF_pleasant_weather,HEATHROW_pleasant_weather,KASSEL_pleasant_weather,LJUBLJANA_pleasant_weather,MAASTRICHT_pleasant_weather,MADRID_pleasant_weather,MUNCHENB_pleasant_weather,OSLO_pleasant_weather,SONNBLICK_pleasant_weather,STOCKHOLM_pleasant_weather,VALENTIA_pleasant_weather
0,19600101,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,19600102,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,19600103,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,19600104,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,19600105,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [31]:
# drop unneeded column from second dataset
prediction.drop(columns = 'DATE', inplace = True)

In [32]:
# confirm drop
prediction.head()

,BASEL_pleasant_weather,BELGRADE_pleasant_weather,BUDAPEST_pleasant_weather,DEBILT_pleasant_weather,DUSSELDORF_pleasant_weather,HEATHROW_pleasant_weather,KASSEL_pleasant_weather,LJUBLJANA_pleasant_weather,MAASTRICHT_pleasant_weather,MADRID_pleasant_weather,MUNCHENB_pleasant_weather,OSLO_pleasant_weather,SONNBLICK_pleasant_weather,STOCKHOLM_pleasant_weather,VALENTIA_pleasant_weather
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [33]:
prediction.shape

(22950, 15)

In [34]:
# Export cleaned dataset
unscaled.to_csv(os.path.join(path, '02 Data', 'Prepared Data', 'weather_cleaned.csv'), index=False)

#### 3. Data Reshaping

In [35]:
# Creat an 'X' matrix by reloading and naming our data 'X'
X=pd.read_csv(os.path.join(path, '02 Data', 'Prepared Data', 'weather_cleaned.csv'), index_col=False)

In [36]:
X.head()

,BASEL_cloud_cover,BASEL_humidity,BASEL_pressure,BASEL_global_radiation,BASEL_precipitation,BASEL_sunshine,BASEL_temp_mean,BASEL_temp_min,BASEL_temp_max,BELGRADE_cloud_cover,BELGRADE_humidity,BELGRADE_pressure,BELGRADE_global_radiation,BELGRADE_precipitation,BELGRADE_sunshine,BELGRADE_temp_mean,BELGRADE_temp_min,BELGRADE_temp_max,BUDAPEST_cloud_cover,BUDAPEST_humidity,BUDAPEST_pressure,BUDAPEST_global_radiation,BUDAPEST_precipitation,BUDAPEST_sunshine,BUDAPEST_temp_mean,BUDAPEST_temp_min,BUDAPEST_temp_max,DEBILT_cloud_cover,DEBILT_humidity,DEBILT_pressure,DEBILT_global_radiation,DEBILT_precipitation,DEBILT_sunshine,DEBILT_temp_mean,DEBILT_temp_min,DEBILT_temp_max,DUSSELDORF_cloud_cover,DUSSELDORF_humidity,DUSSELDORF_pressure,DUSSELDORF_global_radiation,DUSSELDORF_precipitation,DUSSELDORF_sunshine,DUSSELDORF_temp_mean,DUSSELDORF_temp_min,DUSSELDORF_temp_max,HEATHROW_cloud_cover,HEATHROW_humidity,HEATHROW_pressure,HEATHROW_global_radiation,HEATHROW_precipitation,HEATHROW_sunshine,HEATHROW_temp_mean,HEATHROW_temp_min,HEATHROW_temp_max,KASSEL_cloud_cover,KASSEL_humidity,KASSEL_pressure,KASSEL_global_radiation,KASSEL_precipitation,KASSEL_sunshine,KASSEL_temp_mean,KASSEL_temp_min,KASSEL_temp_max,LJUBLJANA_cloud_cover,LJUBLJANA_humidity,LJUBLJANA_pressure,LJUBLJANA_global_radiation,LJUBLJANA_precipitation,LJUBLJANA_sunshine,LJUBLJANA_temp_mean,LJUBLJANA_temp_min,LJUBLJANA_temp_max,MAASTRICHT_cloud_cover,MAASTRICHT_humidity,MAASTRICHT_pressure,MAASTRICHT_global_radiation,MAASTRICHT_precipitation,MAASTRICHT_sunshine,MAASTRICHT_temp_mean,MAASTRICHT_temp_min,MAASTRICHT_temp_max,MADRID_cloud_cover,MADRID_humidity,MADRID_pressure,MADRID_global_radiation,MADRID_precipitation,MADRID_sunshine,MADRID_temp_mean,MADRID_temp_min,MADRID_temp_max,MUNCHENB_cloud_cover,MUNCHENB_humidity,MUNCHENB_pressure,MUNCHENB_global_radiation,MUNCHENB_precipitation,MUNCHENB_sunshine,MUNCHENB_temp_mean,MUNCHENB_temp_min,MUNCHENB_temp_max,OSLO_cloud_cover,OSLO_humidity,OSLO_pressure,OSLO_global_radiation,OSLO_precipitation,OSLO_sunshine,OSLO_temp_mean,OSLO_temp_min,OSLO_temp_max,SONNBLICK_cloud_cover,SONNBLICK_humidity,SONNBLICK_pressure,SONNBLICK_global_radiation,SONNBLICK_precipitation,SONNBLICK_sunshine,SONNBLICK_temp_mean,SONNBLICK_temp_min,SONNBLICK_temp_max,STOCKHOLM_cloud_cover,STOCKHOLM_humidity,STOCKHOLM_pressure,STOCKHOLM_global_radiation,STOCKHOLM_precipitation,STOCKHOLM_sunshine,STOCKHOLM_temp_mean,STOCKHOLM_temp_min,STOCKHOLM_temp_max,VALENTIA_cloud_cover,VALENTIA_humidity,VALENTIA_pressure,VALENTIA_global_radiation,VALENTIA_precipitation,VALENTIA_sunshine,VALENTIA_temp_mean,VALENTIA_temp_min,VALENTIA_temp_max
0,7,0.85,1.018,0.32,0.09,0.7,6.5,0.8,10.9,1,0.81,1.0195,0.88,0.00,7.0,3.7,-0.9,7.9,4,0.67,1.017,0.44,0.01,2.3,2.4,-0.4,5.1,7,0.85,1.0032,0.07,0.25,0.0,9.3,7.4,11.0,8,0.83,1.0161,0.12,0.08,0.0,10.0,7.0,11.5,7,0.91,1.0010,0.13,0.22,0.0,10.6,9.4,8.3,8,0.82,1.0094,0.28,0.48,1.6,7.9,3.9,9.4,8,1.00,1.0173,0.20,0.00,0.0,-0.6,-1.9,0.5,7,0.83,1.0063,0.22,0.32,1.0,9.5,8.5,11.1,6,0.92,1.0260,0.53,0.0,1.4,7.6,4.4,10.8,5,0.67,1.018,0.20,0.10,0.0,6.9,1.1,10.4,8,0.98,0.9978,0.04,1.14,0.0,4.9,3.8,5.9,4,0.73,1.0304,0.48,0.01,2.3,-5.9,-8.5,-3.2,5,0.98,1.0114,0.05,0.32,0.0,4.2,2.2,4.9,5,0.88,1.0003,0.45,0.34,4.7,8.5,6.0,10.9
1,6,0.84,1.018,0.36,1.05,1.1,6.1,3.3,10.1,6,0.84,1.0172,0.25,0.00,0.0,2.9,2.2,4.4,4,0.67,1.017,0.18,0.31,0.0,2.3,1.4,3.1,8,0.90,1.0056,0.14,0.06,0.1,7.7,6.4,8.3,8,0.89,1.0161,0.18,0.66,0.5,8.2,7.4,11.0,7,0.98,1.0051,0.13,0.23,0.0,6.1,3.9,10.6,8,0.86,1.0086,0.12,0.27,0.0,7.7,6.8,9.1,6,0.94,1.0173,0.56,0.13,3.2,2.1,-1.3,5.5,8,0.92,1.0062,0.17,1.34,0.4,8.6,7.5,9.9,7,0.86,1.0254,0.46,0.0,0.9,9.8,7.4,12.2,6,0.72,1.018,0.61,0.30,5.1,6.2,4.2,10.2,8,0.62,1.0139,0.04,0.00,0.0,3.4,2.8,4.9,6,0.97,1.0292,0.21,0.61,0.0,-9.5,-10.5,-8.5,5,0.62,1.0114,0.05,0.06,0.0,4.0,3.0,5.0,7,0.91,1.0007,0.25,0.84,0.7,8.9,5.6,12.1
2,8,0.90,1.018,0.18,0.30,0.0,8.5,5.1,9.9,6,0.77,1.0179,0.67,0.00,3.5,3.1,-0.5,6.4,4,0.67,1.017,0.30,0.00,0.6,2.7,1.7,5.3,6,0.92,1.0165,0.28,0.01,3.0,6.8,4.6,9.9,7,0.95,1.0161,0.12,0.07,0.0,7.1,6.9,9.1,8,0.96,1.0166,0.15,0.07,0.1,8.4,6.1,12.2,7,0.91,1.0129,0.12,0.60,0.0,6.5,6.0,8.0,8,0.96,1.0173,0.20,0.12,0.0,4.6,0.9,6.3,7,0.97,1.0167,0.12,0.46,0.0,6.9,5.5,9.9,5,0.90,1.0287,0.63,0.0,2.3,8.6,6.4,10.8,6,0.91,1.018,0.20,0.30,0.0,5.8,4.0,8.0,8,0.69,1.0234,0.04,0.08,0.0,1.9,0.6,3.1,8,0.93,1.0320,0.21,3.20,0.0,-9.5,-10.0,-8.9,5,0.69,1.0114,0.05,0.02,0.0,2.4,1.3,4.1,7,0.91,1.0096,0.17,0.08,0.1,10.5,8.1,12.9
3,3,0.92,1.018,0.58,0.00,4.1,6.3,3.8,10.6,8,0.93,1.0268,0.25,0.00,0.0,2.0,-2.0,3.0,4,0.67,1.017,0.19,0.00,0.0,2.0,0.4,4.4,8,0.95,1.0265,0.08,0.09,0.0,6.7,3.6,10.1,8,0.86,1.0161,0.12,0.02,0.0,6.8,3.6,8.0,8,0.98,1.0230,0.13,0.00,0.0,9.4,6.7,8.9,8,0.87,1.0290,0.12,0.00,0.0,5.8,5.2,6.5,6,0.94,1.0173,0.49,0.00,2.2,3.2,1.0,7.0,7,0.89,1.0277,0.16,0.00,0.3,7.0,3.0,10.0,0,0.75,1.0281,1.16,0.0,8.7,10.3,4.5,16.1,6,0.90,1.018,0.20,0.01,0.0,3.9,3.2,5.4,8,0.98,1.0244,0.04,0.35,0.0,3.0,0.4,4.9,5,0.93,1.0443,0.22,1.10,0.0,-11.5,-12.9,-10.0,5,0.98,1.0114,0.05,0.00,0.0,1.2,0.4,2.3,7,0.86,1.0184,0.13,0.98,0.0,7.4,7.3,10.6
4,6,0.95,1.018,0.65,0.14,5.4,3.0,-0.7,6.0,8,0.99,1.0286,0.25,0.06,0.0,2.0,0.7,2.8,4,0.67,1.017,0.19,0.00,0.0,2.5,1.1,5.3,6,0.90,1.0243,0.04,0.39,0.0,8.0,2.4,11.2,7,0.92,1.0161,0.12,0.62,0.0,7.7,6.2,11.0,5,0.84,1.0275,0.30,0.00,2.1,8.9,8.9,7.2,7,0.86,1.0262,0.13,0.71,0.0,5.4,3.7,6.0,7,0.94,1.0173,0.20,0.00,0.0,3.6,0.4,4.8,7,0.92,1.0259,0.12,0.56,0.0,8.1,2.5,11.1,2,0.64,1.0269,1.10,0.0,7.8,12.1,8.2,16.0,5,0.85,1.018,0.65,0.96,5.6,1.8,-3.0,6.0,8,0.96,1.0092,0.05,0.26,0.0,3.7,2.9,4.9,2,0.75,1.0430,0.72,0.01,6.1,-9.3,-12.0,-6.5,5,0.96,1.0114,0.05,1.32,0.0,3.3,0.8,4.3,3,0.80,1.0328,0.46,0.00,5.7,5.7,3.0,8.4

In [37]:
y = prediction

In [38]:
X.shape

(22950, 135)

In [39]:
# Turn X and y into arrays
X = np.array(X)
y = np.array(y)
X

array([[ 7.    ,  0.85  ,  1.018 , ...,  8.5   ,  6.    , 10.9   ],
       [ 6.    ,  0.84  ,  1.018 , ...,  8.9   ,  5.6   , 12.1   ],
       [ 8.    ,  0.9   ,  1.018 , ..., 10.5   ,  8.1   , 12.9   ],
       ...,
       [ 4.    ,  0.76  ,  1.0227, ..., 10.7   ,  7.9   , 13.5   ],
       [ 5.    ,  0.8   ,  1.0212, ..., 10.7   ,  7.9   , 13.5   ],
       [ 5.    ,  0.84  ,  1.0193, ..., 10.7   ,  7.9   , 13.5   ]])

In [40]:
X = X.reshape(-1,15,9)

In [41]:
# Verify Shape
X.shape

(22950, 15, 9)

In [42]:
# Verify Shape
y.shape

(22950, 15)

In [43]:
X

array([[[  7.    ,   0.85  ,   1.018 , ...,   6.5   ,   0.8   ,
          10.9   ],
        [  1.    ,   0.81  ,   1.0195, ...,   3.7   ,  -0.9   ,
           7.9   ],
        [  4.    ,   0.67  ,   1.017 , ...,   2.4   ,  -0.4   ,
           5.1   ],
        ...,
        [  4.    ,   0.73  ,   1.0304, ...,  -5.9   ,  -8.5   ,
          -3.2   ],
        [  5.    ,   0.98  ,   1.0114, ...,   4.2   ,   2.2   ,
           4.9   ],
        [  5.    ,   0.88  ,   1.0003, ...,   8.5   ,   6.    ,
          10.9   ]],

       [[  6.    ,   0.84  ,   1.018 , ...,   6.1   ,   3.3   ,
          10.1   ],
        [  6.    ,   0.84  ,   1.0172, ...,   2.9   ,   2.2   ,
           4.4   ],
        [  4.    ,   0.67  ,   1.017 , ...,   2.3   ,   1.4   ,
           3.1   ],
        ...,
        [  6.    ,   0.97  ,   1.0292, ...,  -9.5   , -10.5   ,
          -8.5   ],
        [  5.    ,   0.62  ,   1.0114, ...,   4.    ,   3.    ,
           5.    ],
        [  7.    ,   0.91  ,   1.0007, ...,   8.9   ,   5.6   ,
          12.1   ]],

       [[  8.    ,   0.9   ,   1.018 , ...,   8.5   ,   5.1   ,
           9.9   ],
        [  6.    ,   0.77  ,   1.0179, ...,   3.1   ,  -0.5   ,
           6.4   ],
        [  4.    ,   0.67  ,   1.017 , ...,   2.7   ,   1.7   ,
           5.3   ],
        ...,
        [  8.    ,   0.93  ,   1.032 , ...,  -9.5   , -10.    ,
          -8.9   ],
        [  5.    ,   0.69  ,   1.0114, ...,   2.4   ,   1.3   ,
           4.1   ],
        [  7.    ,   0.91  ,   1.0096, ...,  10.5   ,   8.1   ,
          12.9   ]],

       ...,

       [[  4.    ,   0.76  ,   1.0227, ...,  16.7   ,  13.1   ,
          22.4   ],
        [  2.    ,   0.68  ,   1.0278, ...,  13.4   ,   8.6   ,
          18.2   ],
        [  4.    ,   0.67  ,   1.017 , ...,  11.7   ,   7.9   ,
          16.2   ],
        ...,
        [  3.    ,   0.84  ,   1.0263, ...,   3.3   ,   2.1   ,
           4.5   ],
        [  5.    ,   0.85  ,   1.0059, ...,  13.1   ,  12.1   ,
          14.4   ],
        [  5.    ,   0.82  ,   1.0142, ...,  10.7   ,   7.9   ,
          13.5   ]],

       [[  5.    ,   0.8   ,   1.0212, ...,  15.4   ,  11.6   ,
          21.1   ],
        [  1.    ,   0.68  ,   1.0238, ...,  15.    ,   9.1   ,
          20.9   ],
        [  4.    ,   0.67  ,   1.017 , ...,  11.7   ,   7.9   ,
          16.2   ],
        ...,
        [  3.    ,   0.84  ,   1.0263, ...,   3.4   ,   2.7   ,
           4.1   ],
        [  5.    ,   0.94  ,   1.016 , ...,   7.5   ,   5.1   ,
          12.4   ],
        [  5.    ,   0.82  ,   1.0142, ...,  10.7   ,   7.9   ,
          13.5   ]],

       [[  5.    ,   0.84  ,   1.0193, ...,  13.5   ,   9.9   ,
          19.2   ],
        [  4.    ,   0.68  ,   1.0235, ...,  14.4   ,  10.4   ,
          18.4   ],
        [  4.    ,   0.67  ,   1.017 , ...,  11.7   ,   7.9   ,
          16.2   ],
        ...,
        [  4.    ,   0.84  ,   1.0263, ...,   1.7   ,   0.7   ,
           2.7   ],
        [  5.    ,   0.97  ,   1.0164, ...,   9.7   ,   5.    ,
          12.6   ],
        [  5.    ,   0.82  ,   1.0142, ...,  10.7   ,   7.9   ,
          13.5   ]]])

#### 4. Data Splitting

In [44]:
# Split data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state = 42)

In [45]:
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(17212, 15, 9) (17212, 15)
(5738, 15, 9) (5738, 15)

#### 5. Keras Model Creation

In [47]:
epochs = 30
batch_size = 16
n_hidden = 32

timesteps = len(X_train[0])
input_dim = len(X_train[0][0])
n_classes = len(y_train[0])

model = Sequential()
model.add(Conv1D(n_hidden, kernel_size=2, activation='relu', input_shape=(timesteps, input_dim)))
model.add(Dense(16, activation='relu'))
model.add(MaxPooling1D())
model.add(Flatten())
model.add(Dense(n_classes, activation='softmax')) # Options: sigmoid, tanh, softmax, relu

In [48]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d (Conv1D)                 │ (None, 14, 32)         │           608 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 14, 16)         │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d (MaxPooling1D)    │ (None, 7, 16)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 112)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 15)             │         1,695 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,831 (11.06 KB)

 Trainable params: 2,831 (11.06 KB)

 Non-trainable params: 0 (0.00 B)

#### 6. Compiling and Running Model

In [49]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [50]:
model.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, verbose=2)

Epoch 1/30
1076/1076 - 3s - 3ms/step - accuracy: 0.1096 - loss: 4715.2090
Epoch 2/30
1076/1076 - 2s - 2ms/step - accuracy: 0.1297 - loss: 50874.9141
Epoch 3/30
1076/1076 - 2s - 2ms/step - accuracy: 0.1331 - loss: 158111.3594
Epoch 4/30
1076/1076 - 2s - 2ms/step - accuracy: 0.1321 - loss: 362184.7500
Epoch 5/30
1076/1076 - 2s - 2ms/step - accuracy: 0.1317 - loss: 647330.1250
Epoch 6/30
1076/1076 - 2s - 2ms/step - accuracy: 0.1279 - loss: 1034453.3125
Epoch 7/30
1076/1076 - 2s - 2ms/step - accuracy: 0.1325 - loss: 1528300.0000
Epoch 8/30
1076/1076 - 2s - 2ms/step - accuracy: 0.1339 - loss: 2117265.2500
Epoch 9/30
1076/1076 - 2s - 2ms/step - accuracy: 0.1350 - loss: 2826725.7500
Epoch 10/30
1076/1076 - 2s - 2ms/step - accuracy: 0.1337 - loss: 3675577.0000
Epoch 11/30
1076/1076 - 2s - 2ms/step - accuracy: 0.1309 - loss: 4688194.0000
Epoch 12/30
1076/1076 - 2s - 2ms/step - accuracy: 0.1313 - loss: 5902675.0000
Epoch 13/30
1076/1076 - 2s - 2ms/step - accuracy: 0.1346 - loss: 7151131.5000
Epoch 14/30
1076/1076 - 2s - 2ms/step - accuracy: 0.1343 - loss: 8686927.0000
Epoch 15/30
1076/1076 - 2s - 2ms/step - accuracy: 0.1371 - loss: 10349465.0000
Epoch 16/30
1076/1076 - 2s - 2ms/step - accuracy: 0.1379 - loss: 12230615.0000
Epoch 17/30
1076/1076 - 2s - 2ms/step - accuracy: 0.1357 - loss: 14260941.0000
Epoch 18/30
1076/1076 - 2s - 2ms/step - accuracy: 0.1371 - loss: 16531856.0000
Epoch 19/30
1076/1076 - 2s - 2ms/step - accuracy: 0.1339 - loss: 19003112.0000
Epoch 20/30
1076/1076 - 2s - 2ms/step - accuracy: 0.1387 - loss: 21735420.0000
Epoch 21/30
1076/1076 - 2s - 2ms/step - accuracy: 0.1390 - loss: 24603802.0000
Epoch 22/30
1076/1076 - 2s - 2ms/step - accuracy: 0.1354 - loss: 27712898.0000
Epoch 23/30
1076/1076 - 2s - 2ms/step - accuracy: 0.1343 - loss: 31101324.0000
Epoch 24/30
1076/1076 - 2s - 2ms/step - accuracy: 0.1403 - loss: 34730040.0000
Epoch 25/30
1076/1076 - 2s - 2ms/step - accuracy: 0.1350 - loss: 38657412.0000
Epoch 26/30
1076/1076 - 2s - 2ms/step - accuracy: 0.1369 - loss: 42969256.0000
Epoch 27/30
1076/1076 - 2s - 2ms/step - accuracy: 0.1392 - loss: 47426496.0000
Epoch 28/30
1076/1076 - 2s - 2ms/step - accuracy: 0.1359 - loss: 52193864.0000
Epoch 29/30
1076/1076 - 2s - 2ms/step - accuracy: 0.1337 - loss: 57272272.0000
Epoch 30/30
1076/1076 - 2s - 2ms/step - accuracy: 0.1358 - loss: 62633780.0000

#### Confusion Matrix Creation

In [51]:
# Define list of stations names

stations = {
0: 'BASEL',
1: 'BELGRADE',
2: 'BUDAPEST',
3: 'DEBILT',
4: 'DUSSELDORF',
5: 'HEATHROW',
6: 'KASSEL',
7: 'LJUBLJANA',
8: 'MAASTRICHT',
9: 'MADRID',
10: 'MUNCHENB',
11: 'OSLO',
12: 'SONNBLICK',
13: 'STOCKHOLM',
14: 'VALENTIA'

}

In [52]:
def confusion_matrix(y_true, y_pred):
    y_true = pd.Series([stations[y] for y in np.argmax(y_true, axis=1)])
    y_pred = pd.Series([stations[y] for y in np.argmax(y_pred, axis=1)])

    return pd.crosstab(y_true, y_pred, rownames=['True'], colnames=['Pred'])

In [53]:
# Evaluate
print(confusion_matrix(y_test, model.predict(X_test)))

180/180 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
Pred        BASEL  BELGRADE  BUDAPEST  DEBILT  DUSSELDORF  HEATHROW  KASSEL  \
True
BASEL         238      2210         1      67         119       111      37
BELGRADE       21       966         0       0           1         0       0
BUDAPEST       13       171         0       1           0         0       0
DEBILT          9        49         0       0           0         1       0
DUSSELDORF      6        13         0       0           0         0       0
HEATHROW       16        39         0       0           1         0       0
KASSEL          0         8         0       0           0         0       0
LJUBLJANA       6        51         0       0           0         0       0
MAASTRICHT      0         7         0       0           0         0       0
MADRID         60       279         0       1           5         6       0
MUNCHENB        0         7         0       0           0         0       0
OSLO            0         3         0       0           0         0       0
STOCKHOLM       0         4         0       0           0         0       0
VALENTIA        0         0         0       1           0         0       0

Pred        LJUBLJANA  MAASTRICHT  MADRID  MUNCHENB  OSLO  SONNBLICK  \
True
BASEL             229         231      14       180    79          9
BELGRADE            0          58       0         0     6          0
BUDAPEST            0          16       0         0     1          0
DEBILT              0          15       0         0     0          0
DUSSELDORF          0           7       0         0     0          0
HEATHROW            1          13       3         0     3          0
KASSEL              0           2       0         0     1          0
LJUBLJANA           0           1       0         0     0          0
MAASTRICHT          1           1       0         0     0          0
MADRID             14          29      31         4     7          0
MUNCHENB            0           0       0         0     1          0
OSLO                0           0       0         0     1          0
STOCKHOLM           0           0       0         0     0          0
VALENTIA            0           0       0         0     0          0

Pred        STOCKHOLM  VALENTIA
True
BASEL             121        36
BELGRADE           40         0
BUDAPEST           12         0
DEBILT              8         0
DUSSELDORF          3         0
HEATHROW            6         0
KASSEL              0         0
LJUBLJANA           3         0
MAASTRICHT          0         0
MADRID             22         0
MUNCHENB            0         0
OSLO                1         0
STOCKHOLM           0         0
VALENTIA            0         0

#### 8. Keras Model Retrials

In [54]:
epochs = 30
batch_size = 16
n_hidden = 4

timesteps = len(X_train[0])
input_dim = len(X_train[0][0])
n_classes = len(y_train[0])

model = Sequential()
model.add(Conv1D(n_hidden, kernel_size=2, activation='relu', input_shape=(timesteps, input_dim)))
model.add(Dense(16, activation='relu'))
model.add(MaxPooling1D())
model.add(Flatten())
model.add(Dense(n_classes, activation='softmax')) # Options: sigmoid, tanh, softmax, relu

In [55]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_1 (Conv1D)               │ (None, 14, 4)          │            76 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 14, 16)         │            80 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_1 (MaxPooling1D)  │ (None, 7, 16)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_1 (Flatten)             │ (None, 112)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 15)             │         1,695 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,851 (7.23 KB)

 Trainable params: 1,851 (7.23 KB)

 Non-trainable params: 0 (0.00 B)

In [56]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [57]:
model.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, verbose=2)

Epoch 1/30
1076/1076 - 3s - 2ms/step - accuracy: 0.1178 - loss: 1103.3755
Epoch 2/30
1076/1076 - 2s - 2ms/step - accuracy: 0.1114 - loss: 10684.3340
Epoch 3/30
1076/1076 - 2s - 2ms/step - accuracy: 0.1120 - loss: 34016.9648
Epoch 4/30
1076/1076 - 2s - 2ms/step - accuracy: 0.1160 - loss: 73014.6484
Epoch 5/30
1076/1076 - 2s - 2ms/step - accuracy: 0.1149 - loss: 124286.6641
Epoch 6/30
1076/1076 - 2s - 2ms/step - accuracy: 0.1231 - loss: 195236.4844
Epoch 7/30
1076/1076 - 2s - 2ms/step - accuracy: 0.1217 - loss: 275215.5312
Epoch 8/30
1076/1076 - 2s - 2ms/step - accuracy: 0.1185 - loss: 376829.0312
Epoch 9/30
1076/1076 - 2s - 2ms/step - accuracy: 0.1268 - loss: 491702.2812
Epoch 10/30
1076/1076 - 2s - 2ms/step - accuracy: 0.1264 - loss: 639553.8125
Epoch 11/30
1076/1076 - 2s - 2ms/step - accuracy: 0.1256 - loss: 796846.4375
Epoch 12/30
1076/1076 - 2s - 2ms/step - accuracy: 0.1258 - loss: 983726.2500
Epoch 13/30
1076/1076 - 2s - 2ms/step - accuracy: 0.1256 - loss: 1187796.6250
Epoch 14/30
1076/1076 - 2s - 2ms/step - accuracy: 0.1262 - loss: 1444701.3750
Epoch 15/30
1076/1076 - 2s - 2ms/step - accuracy: 0.1292 - loss: 1706625.5000
Epoch 16/30
1076/1076 - 2s - 1ms/step - accuracy: 0.1287 - loss: 2006708.7500
Epoch 17/30
1076/1076 - 2s - 2ms/step - accuracy: 0.1248 - loss: 2336632.0000
Epoch 18/30
1076/1076 - 2s - 2ms/step - accuracy: 0.1272 - loss: 2681961.0000
Epoch 19/30
1076/1076 - 2s - 2ms/step - accuracy: 0.1249 - loss: 3112950.2500
Epoch 20/30
1076/1076 - 2s - 2ms/step - accuracy: 0.1253 - loss: 3540001.0000
Epoch 21/30
1076/1076 - 2s - 1ms/step - accuracy: 0.1267 - loss: 3992878.5000
Epoch 22/30
1076/1076 - 2s - 2ms/step - accuracy: 0.1264 - loss: 4532760.0000
Epoch 23/30
1076/1076 - 2s - 2ms/step - accuracy: 0.1251 - loss: 5029640.0000
Epoch 24/30
1076/1076 - 2s - 2ms/step - accuracy: 0.1268 - loss: 5620774.5000
Epoch 25/30
1076/1076 - 2s - 1ms/step - accuracy: 0.1244 - loss: 6287658.0000
Epoch 26/30
1076/1076 - 2s - 2ms/step - accuracy: 0.1269 - loss: 6952550.0000
Epoch 27/30
1076/1076 - 2s - 1ms/step - accuracy: 0.1280 - loss: 7709378.0000
Epoch 28/30
1076/1076 - 2s - 1ms/step - accuracy: 0.1243 - loss: 8542036.0000
Epoch 29/30
1076/1076 - 2s - 2ms/step - accuracy: 0.1256 - loss: 9298093.0000
Epoch 30/30
1076/1076 - 2s - 2ms/step - accuracy: 0.1241 - loss: 10217422.0000

In [58]:
def confusion_matrix(y_true, y_pred):
    y_true = pd.Series([stations[y] for y in np.argmax(y_true, axis=1)])
    y_pred = pd.Series([stations[y] for y in np.argmax(y_pred, axis=1)])

    return pd.crosstab(y_true, y_pred, rownames=['True'], colnames=['Pred'])

In [59]:
# Evaluate

print(confusion_matrix(y_test, model.predict(X_test)))

180/180 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
Pred        BASEL  BELGRADE  BUDAPEST  DEBILT  DUSSELDORF  HEATHROW  KASSEL  \
True
BASEL           1       158         3     947          10        97      35
BELGRADE        0        29         0     162           0         2       5
BUDAPEST        0         3         0      31           0         0       0
DEBILT          0         0         0      27           0         0       0
DUSSELDORF      0         0         0      12           0         0       0
HEATHROW        0         0         0      25           0         0       0
KASSEL          0         0         0       3           0         0       0
LJUBLJANA       0         0         0       6           0         0       0
MAASTRICHT      0         0         0       0           0         0       0
MADRID          0         1         0      82           0         7       2
MUNCHENB        0         0         0       0           0         0       0
OSLO            0         0         0       1           0         0       0
STOCKHOLM       0         0         0       0           0         0       0
VALENTIA        0         0         0       1           0         0       0

Pred        LJUBLJANA  MADRID  MUNCHENB  OSLO  SONNBLICK  STOCKHOLM  VALENTIA
True
BASEL               5    1138      1222    29          2         23        12
BELGRADE            0     462       430     2          0          0         0
BUDAPEST            0     137        43     0          0          0         0
DEBILT              0      27        28     0          0          0         0
DUSSELDORF          0      12         5     0          0          0         0
HEATHROW            0      52         5     0          0          0         0
KASSEL              0       3         5     0          0          0         0
LJUBLJANA           0      46         9     0          0          0         0
MAASTRICHT          0       4         5     0          0          0         0
MADRID              0     331        32     2          0          1         0
MUNCHENB            0       6         2     0          0          0         0
OSLO                0       3         0     1          0          0         0
STOCKHOLM           0       2         2     0          0          0         0
VALENTIA            0       0         0     0          0          0         0

#### Softmax isn’t giving good results, so we will try using tanh, sigmoid, and relu instead.

In [60]:
epochs = 30
batch_size = 16
n_hidden = 128

timesteps = len(X_train[0])
input_dim = len(X_train[0][0])
n_classes = len(y_train[0])

model = Sequential()
model.add(Conv1D(n_hidden, kernel_size=2, activation='relu', input_shape=(timesteps, input_dim)))
model.add(Dense(16, activation='relu'))
model.add(MaxPooling1D())
model.add(Flatten())
model.add(Dense(n_classes, activation='tanh')) # Options: sigmoid, tanh, softmax, relu

In [61]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_2 (Conv1D)               │ (None, 14, 128)        │         2,432 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 14, 16)         │         2,064 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_2 (MaxPooling1D)  │ (None, 7, 16)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_2 (Flatten)             │ (None, 112)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 15)             │         1,695 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 6,191 (24.18 KB)

 Trainable params: 6,191 (24.18 KB)

 Non-trainable params: 0 (0.00 B)

In [62]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [63]:
model.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, verbose=2)

Epoch 1/30
1076/1076 - 3s - 3ms/step - accuracy: 0.0060 - loss: 23.6133
Epoch 2/30
1076/1076 - 2s - 2ms/step - accuracy: 0.0106 - loss: 25.9434
Epoch 3/30
1076/1076 - 2s - 2ms/step - accuracy: 0.0150 - loss: 22.6451
Epoch 4/30
1076/1076 - 2s - 2ms/step - accuracy: 0.0150 - loss: 22.6470
Epoch 5/30
1076/1076 - 2s - 2ms/step - accuracy: 0.0149 - loss: 22.6479
Epoch 6/30
1076/1076 - 2s - 2ms/step - accuracy: 0.0149 - loss: 22.6488
Epoch 7/30
1076/1076 - 2s - 2ms/step - accuracy: 0.0149 - loss: 22.6488
Epoch 8/30
1076/1076 - 2s - 2ms/step - accuracy: 0.0149 - loss: 22.6498
Epoch 9/30
1076/1076 - 2s - 2ms/step - accuracy: 0.0149 - loss: 22.6498
Epoch 10/30
1076/1076 - 2s - 2ms/step - accuracy: 0.0149 - loss: 22.6498
Epoch 11/30
1076/1076 - 2s - 2ms/step - accuracy: 0.0149 - loss: 22.6498
Epoch 12/30
1076/1076 - 2s - 2ms/step - accuracy: 0.0149 - loss: 22.6498
Epoch 13/30
1076/1076 - 2s - 2ms/step - accuracy: 0.0149 - loss: 22.6488
Epoch 14/30
1076/1076 - 2s - 2ms/step - accuracy: 0.0149 - loss: 22.6488
Epoch 15/30
1076/1076 - 2s - 2ms/step - accuracy: 0.0149 - loss: 22.6498
Epoch 16/30
1076/1076 - 2s - 2ms/step - accuracy: 0.0149 - loss: 22.6507
Epoch 17/30
1076/1076 - 2s - 2ms/step - accuracy: 0.0146 - loss: 22.6423
Epoch 18/30
1076/1076 - 2s - 2ms/step - accuracy: 0.0144 - loss: 22.6329
Epoch 19/30
1076/1076 - 2s - 2ms/step - accuracy: 0.0144 - loss: 22.6329
Epoch 20/30
1076/1076 - 2s - 2ms/step - accuracy: 0.0144 - loss: 22.6329
Epoch 21/30
1076/1076 - 2s - 2ms/step - accuracy: 0.0144 - loss: 22.6329
Epoch 22/30
1076/1076 - 2s - 2ms/step - accuracy: 0.0144 - loss: 22.6329
Epoch 23/30
1076/1076 - 2s - 2ms/step - accuracy: 0.0144 - loss: 22.6329
Epoch 24/30
1076/1076 - 2s - 2ms/step - accuracy: 0.0144 - loss: 22.6329
Epoch 25/30
1076/1076 - 2s - 2ms/step - accuracy: 0.0144 - loss: 22.6329
Epoch 26/30
1076/1076 - 2s - 2ms/step - accuracy: 0.0144 - loss: 22.6329
Epoch 27/30
1076/1076 - 2s - 2ms/step - accuracy: 0.0144 - loss: 22.6329
Epoch 28/30
1076/1076 - 2s - 2ms/step - accuracy: 0.0144 - loss: 22.6329
Epoch 29/30
1076/1076 - 2s - 2ms/step - accuracy: 0.0144 - loss: 22.6329
Epoch 30/30
1076/1076 - 2s - 2ms/step - accuracy: 0.0144 - loss: 22.6329

In [64]:
def confusion_matrix(y_true, y_pred):
    y_true = pd.Series([stations[y] for y in np.argmax(y_true, axis=1)])
    y_pred = pd.Series([stations[y] for y in np.argmax(y_pred, axis=1)])

    return pd.crosstab(y_true, y_pred, rownames=['True'], colnames=['Pred'])

In [65]:
# Evaluate

print(confusion_matrix(y_test, model.predict(X_test)))

180/180 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
Pred        DEBILT  DUSSELDORF  KASSEL  LJUBLJANA  MUNCHENB  OSLO  STOCKHOLM
True
BASEL         3247         370       7         21         4    14         19
BELGRADE      1091           1       0          0         0     0          0
BUDAPEST       214           0       0          0         0     0          0
DEBILT          82           0       0          0         0     0          0
DUSSELDORF      29           0       0          0         0     0          0
HEATHROW        82           0       0          0         0     0          0
KASSEL          11           0       0          0         0     0          0
LJUBLJANA       61           0       0          0         0     0          0
MAASTRICHT       9           0       0          0         0     0          0
MADRID         452           3       3          0         0     0          0
MUNCHENB         8           0       0          0         0     0          0
OSLO             5           0       0          0         0     0          0
STOCKHOLM        4           0       0          0         0     0          0
VALENTIA         1           0       0          0         0     0          0

##### The loss has improved, but the accuracy remains low, so let’s try modifying the layers.

In [66]:
epochs = 30
batch_size = 16
n_hidden = 64

timesteps = len(X_train[0])
input_dim = len(X_train[0][0])
n_classes = len(y_train[0])

model = Sequential()
model.add(Conv1D(n_hidden, kernel_size=2, activation='relu', input_shape=(timesteps, input_dim)))
model.add(Dense(16, activation='relu'))
model.add(MaxPooling1D())
model.add(Flatten())
model.add(Dense(n_classes, activation='tanh')) # Options: sigmoid, tanh, softmax, relu

In [67]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_3 (Conv1D)               │ (None, 14, 64)         │         1,216 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 14, 16)         │         1,040 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_3 (MaxPooling1D)  │ (None, 7, 16)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_3 (Flatten)             │ (None, 112)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 15)             │         1,695 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,951 (15.43 KB)

 Trainable params: 3,951 (15.43 KB)

 Non-trainable params: 0 (0.00 B)

In [68]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [69]:
model.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, verbose=2)

Epoch 1/30
1076/1076 - 3s - 3ms/step - accuracy: 0.2667 - loss: 28.3958
Epoch 2/30
1076/1076 - 2s - 2ms/step - accuracy: 0.3325 - loss: 18.3336
Epoch 3/30
1076/1076 - 2s - 2ms/step - accuracy: 0.3050 - loss: 17.8356
Epoch 4/30
1076/1076 - 2s - 2ms/step - accuracy: 0.3266 - loss: 17.8421
Epoch 5/30
1076/1076 - 2s - 2ms/step - accuracy: 0.3388 - loss: 18.6222
Epoch 6/30
1076/1076 - 2s - 2ms/step - accuracy: 0.4662 - loss: 23.8584
Epoch 7/30
1076/1076 - 2s - 2ms/step - accuracy: 0.5157 - loss: 25.6043
Epoch 8/30
1076/1076 - 2s - 2ms/step - accuracy: 0.5451 - loss: 22.5721
Epoch 9/30
1076/1076 - 2s - 2ms/step - accuracy: 0.5597 - loss: 21.3566
Epoch 10/30
1076/1076 - 2s - 2ms/step - accuracy: 0.5563 - loss: 21.5553
Epoch 11/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6258 - loss: 27.3367
Epoch 12/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6260 - loss: 27.3367
Epoch 13/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6257 - loss: 27.3367
Epoch 14/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6255 - loss: 27.3367
Epoch 15/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6251 - loss: 27.3367
Epoch 16/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6240 - loss: 27.3367
Epoch 17/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6231 - loss: 27.3367
Epoch 18/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6215 - loss: 27.3367
Epoch 19/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6203 - loss: 27.3367
Epoch 20/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6200 - loss: 27.3367
Epoch 21/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6186 - loss: 27.3367
Epoch 22/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6168 - loss: 27.3367
Epoch 23/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6156 - loss: 27.3367
Epoch 24/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6151 - loss: 27.3367
Epoch 25/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6126 - loss: 27.3367
Epoch 26/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6078 - loss: 27.3367
Epoch 27/30
1076/1076 - 2s - 2ms/step - accuracy: 0.5993 - loss: 27.3367
Epoch 28/30
1076/1076 - 2s - 2ms/step - accuracy: 0.5858 - loss: 27.3367
Epoch 29/30
1076/1076 - 2s - 2ms/step - accuracy: 0.5674 - loss: 27.3367
Epoch 30/30
1076/1076 - 2s - 2ms/step - accuracy: 0.4949 - loss: 27.3367

In [83]:
def confusion_matrix(y_true, y_pred):
    y_true = pd.Series([stations[y] for y in np.argmax(y_true, axis=1)])
    y_pred = pd.Series([stations[y] for y in np.argmax(y_pred, axis=1)])

    return pd.crosstab(y_true, y_pred, rownames=['True'], colnames=['Pred'])

In [84]:
# Evaluate

print(confusion_matrix(y_test, model.predict(X_test)))

180/180 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
Pred        BASEL
True
BASEL        3682
BELGRADE     1092
BUDAPEST      214
DEBILT         82
DUSSELDORF     29
HEATHROW       82
KASSEL         11
LJUBLJANA      61
MAASTRICHT      9
MADRID        458
MUNCHENB        8
OSLO            5
STOCKHOLM       4
VALENTIA        1

##### Loss is not is stable but not as low as I would like, however accuracy is much higher. Trial with sigmoid and relu

In [73]:
epochs = 30
batch_size = 16
n_hidden = 64

timesteps = len(X_train[0])
input_dim = len(X_train[0][0])
n_classes = len(y_train[0])

model = Sequential()
model.add(Conv1D(n_hidden, kernel_size=2, activation='relu', input_shape=(timesteps, input_dim)))
model.add(Dense(16, activation='relu'))
model.add(MaxPooling1D())
model.add(Flatten())
model.add(Dense(n_classes, activation='sigmoid')) # Options: sigmoid, tanh, softmax, relu

In [74]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_4 (Conv1D)               │ (None, 14, 64)         │         1,216 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 14, 16)         │         1,040 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_4 (MaxPooling1D)  │ (None, 7, 16)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_4 (Flatten)             │ (None, 112)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 15)             │         1,695 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,951 (15.43 KB)

 Trainable params: 3,951 (15.43 KB)

 Non-trainable params: 0 (0.00 B)

In [75]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [76]:
model.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, verbose=2)

Epoch 1/30
1076/1076 - 3s - 2ms/step - accuracy: 0.6213 - loss: 12199.7666
Epoch 2/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6416 - loss: 120130.1719
Epoch 3/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6415 - loss: 389904.9375
Epoch 4/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6414 - loss: 843981.8125
Epoch 5/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6414 - loss: 1420145.0000
Epoch 6/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6414 - loss: 2117347.7500
Epoch 7/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6414 - loss: 3016063.2500
Epoch 8/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6414 - loss: 4026805.5000
Epoch 9/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6414 - loss: 5211435.0000
Epoch 10/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6414 - loss: 6594329.5000
Epoch 11/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6414 - loss: 8092324.5000
Epoch 12/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6414 - loss: 9961362.0000
Epoch 13/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6414 - loss: 11846196.0000
Epoch 14/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6414 - loss: 14050615.0000
Epoch 15/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6414 - loss: 16498699.0000
Epoch 16/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6414 - loss: 19202468.0000
Epoch 17/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6414 - loss: 22105400.0000
Epoch 18/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6414 - loss: 25333418.0000
Epoch 19/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6414 - loss: 28689948.0000
Epoch 20/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6414 - loss: 32594744.0000
Epoch 21/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6414 - loss: 36491976.0000
Epoch 22/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6414 - loss: 40811416.0000
Epoch 23/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6414 - loss: 45117640.0000
Epoch 24/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6414 - loss: 50324312.0000
Epoch 25/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6423 - loss: 55302212.0000
Epoch 26/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6440 - loss: 61010780.0000
Epoch 27/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6440 - loss: 66683236.0000
Epoch 28/30
1076/1076 - 3s - 3ms/step - accuracy: 0.6440 - loss: 72650120.0000
Epoch 29/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6440 - loss: 79302600.0000
Epoch 30/30
1076/1076 - 2s - 2ms/step - accuracy: 0.6440 - loss: 86448904.0000

In [77]:
def confusion_matrix(y_true, y_pred):
    y_true = pd.Series([stations[y] for y in np.argmax(y_true, axis=1)])
    y_pred = pd.Series([stations[y] for y in np.argmax(y_pred, axis=1)])

    return pd.crosstab(y_true, y_pred, rownames=['True'], colnames=['Pred'])

In [78]:
# Evaluate

print(confusion_matrix(y_test, model.predict(X_test)))

180/180 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
Pred        BASEL
True
BASEL        3682
BELGRADE     1092
BUDAPEST      214
DEBILT         82
DUSSELDORF     29
HEATHROW       82
KASSEL         11
LJUBLJANA      61
MAASTRICHT      9
MADRID        458
MUNCHENB        8
OSLO            5
STOCKHOLM       4
VALENTIA        1

##### The loss and accuracy are much worse than with tanh, so let’s try using relu instead.

In [79]:
epochs = 15
batch_size = 4
n_hidden = 4

timesteps = len(X_train[0])
input_dim = len(X_train[0][0])
n_classes = len(y_train[0])

model = Sequential()
model.add(Conv1D(n_hidden, kernel_size=2, activation='relu', input_shape=(timesteps, input_dim)))
model.add(Dense(16, activation='relu'))
model.add(MaxPooling1D())
model.add(Flatten())
model.add(Dense(n_classes, activation='relu')) # Options: sigmoid, tanh, softmax, relu

In [80]:
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_5 (Conv1D)               │ (None, 14, 4)          │            76 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_10 (Dense)                │ (None, 14, 16)         │            80 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_5 (MaxPooling1D)  │ (None, 7, 16)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_5 (Flatten)             │ (None, 112)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 15)             │         1,695 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,851 (7.23 KB)

 Trainable params: 1,851 (7.23 KB)

 Non-trainable params: 0 (0.00 B)

In [81]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [82]:
model.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, verbose=2)

Epoch 1/15
4303/4303 - 8s - 2ms/step - accuracy: 0.1306 - loss: 20.2365
Epoch 2/15
4303/4303 - 7s - 2ms/step - accuracy: 0.1611 - loss: 17.8491
Epoch 3/15
4303/4303 - 7s - 2ms/step - accuracy: 0.5838 - loss: nan
Epoch 4/15
4303/4303 - 7s - 2ms/step - accuracy: 0.6440 - loss: nan
Epoch 5/15
4303/4303 - 6s - 1ms/step - accuracy: 0.6440 - loss: nan
Epoch 6/15
4303/4303 - 7s - 2ms/step - accuracy: 0.6440 - loss: nan
Epoch 7/15
4303/4303 - 6s - 1ms/step - accuracy: 0.6440 - loss: nan
Epoch 8/15
4303/4303 - 7s - 2ms/step - accuracy: 0.6440 - loss: nan
Epoch 9/15
4303/4303 - 6s - 1ms/step - accuracy: 0.6440 - loss: nan
Epoch 10/15
4303/4303 - 6s - 1ms/step - accuracy: 0.6440 - loss: nan
Epoch 11/15
4303/4303 - 7s - 2ms/step - accuracy: 0.6440 - loss: nan
Epoch 12/15
4303/4303 - 7s - 2ms/step - accuracy: 0.6440 - loss: nan
Epoch 13/15
4303/4303 - 7s - 2ms/step - accuracy: 0.6440 - loss: nan
Epoch 14/15
4303/4303 - 6s - 2ms/step - accuracy: 0.6440 - loss: nan
Epoch 15/15
4303/4303 - 6s - 1ms/step - accuracy: 0.6440 - loss: nan

In [85]:
def confusion_matrix(y_true, y_pred):
    y_true = pd.Series([stations[y] for y in np.argmax(y_true, axis=1)])
    y_pred = pd.Series([stations[y] for y in np.argmax(y_pred, axis=1)])

    return pd.crosstab(y_true, y_pred, rownames=['True'], colnames=['Pred'])

In [86]:
# Evaluate

print(confusion_matrix(y_test, model.predict(X_test)))

180/180 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
Pred        BASEL
True
BASEL        3682
BELGRADE     1092
BUDAPEST      214
DEBILT         82
DUSSELDORF     29
HEATHROW       82
KASSEL         11
LJUBLJANA      61
MAASTRICHT      9
MADRID        458
MUNCHENB        8
OSLO            5
STOCKHOLM       4
VALENTIA        1